### ISSUE TITLE
Can't install plugin with logstash 2.3.4

### ISSUE THREAD

**Issue by rvrignaud** [logstash-plugins/logstash-output-google_cloud_storage#6] opened 2016-07-30 15:08 UTC
Can't install google_cloud_storage plugin with logstash 2.3.4
I get following error:

```
Error Bundler::InstallError, retrying 1/10
An error occurred while installing google-api-client (0.9.11), and Bundler cannot continue.
Make sure that `gem install google-api-client -v '0.9.11'` succeeds before bundling.
WARNING: SSLSocket#session= is not supported
```
- Version:
  Logstash 2.3.4
- Operating System:
  Ubuntu 16.04
- Steps to Reproduce:

On a fresh ubuntu 16.04 installation (in my case ubuntu:16.04 docker image)

```
export LOGSTASH_MAJOR=2.3
export DEBIAN_FRONTEND=noninteractive


apt-key adv --keyserver ha.pool.sks-keyservers.net --recv-keys 46095ACC8548582C1A2699A9D27D666CD88E42B4
echo "deb http://packages.elastic.co/logstash/${LOGSTASH_MAJOR}/debian stable main" > /etc/apt/sources.list.d/logstash.list
apt-key adv --keyserver ha.pool.sks-keyservers.net --recv-keys EEA14886
echo "deb http://ppa.launchpad.net/webupd8team/java/ubuntu vivid main" > /etc/apt/sources.list.d/java.list
echo "oracle-java8-installer shared/accepted-oracle-license-v1-1 boolean true" | debconf-set-selections

apt-get install -y oracle-java8-installer logstash
/opt/logstash/bin/logstash-plugin install logstash-output-google_cloud_storage
```

**Comment by rvrignaud** [comment] 2016-08-01 14:45
Problem seems to come from unpinned dependencies that dropped ruby 1.9 support.
As a workarround this seem to work:
```
export PATH=/opt/logstash/vendor/jruby/bin:$PATH
/opt/logstash/vendor/jruby/bin/gem install activesupport -v 4.2.7
/opt/logstash/vendor/jruby/bin/gem install google-api-client -v 0.8.6
echo 'gem "google-api-client", "0.8.6"' >> /opt/logstash/Gemfile
/opt/logstash/bin/logstash-plugin install logstash-output-google_cloud_storage
```

**Comment by kureus** [comment] 2016-10-18 13:59
Can confirm the same issue on logstash 2.2.2 on a debian 8 docker container. @rvrignaud workaround allowed successful install.

**Comment by sbadia** [comment] 2016-11-08 16:48
Hi, same issue here, with logstash 2.3.4.
[Addressable](https://rubygems.org/gems/addressable) (a dependency of `google-api-client`, just released a new version the 4 November, `addressable` new version has bumped the dependency on `public_suffix`, but ruby min_requirement for public_suffix is 2.x since [public_suffix 1.4.6](https://rubygems.org/gems/public_suffix/versions/1.4.6) :smile: 

So… new workaround… : 
```bash
export PATH=/opt/logstash/vendor/jruby/bin:$PATH
/opt/logstash/vendor/jruby/bin/gem install activesupport --no-ri --no-rdoc -v 4.2.7
/opt/logstash/vendor/jruby/bin/gem install addressable --no-ri --no-rdoc -v 2.3.8
/opt/logstash/vendor/jruby/bin/gem install google-api-client --no-ri --no-rdoc -v 0.8.6
echo 'gem "addressable", "2.3.8"' >> /opt/logstash/Gemfile
echo 'gem "google-api-client", "0.8.6"' >> /opt/logstash/Gemfile
/opt/logstash/bin/logstash-plugin install logstash-output-google_cloud_storage
```
:sweat:

**Comment by josephlewis42** [comment] 2018-06-01 15:40
Closing this due to the LS version mentioned here being older. SSL issues should be fixed with https://github.com/logstash-plugins/logstash-output-google_cloud_storage/pull/21, but due to an upstream regression, merging that before Logstash 6.3.1 gets released will break it.

**Closed by josephlewis42** 2018-06-01 15:40 UTC
